version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: tgbot
      MYSQL_PASSWORD: qwerty12345
    ports:
      - "3307:3306"